### PR TITLE
Add python-dev dependency to make sure python-config exists

### PR DESCRIPTION
**Pull request by AAlon**
Blocked on https://github.com/ros/rosdistro/pull/21334

### CODE REVIEW

**Comment by malsbat** [comment]
@AAlon, do you want to wait for https://github.com/ros/rosdistro/pull/21334 to be merged first?  An alternative approach would be to fix the dps-for-iot build scripts to only call python-config when the python binding is enabled (which it is not in dps_for_iot_cmake_module).

**Comment by AAlon** [comment]
> @AAlon, do you want to wait for [ros/rosdistro#21334](https://github.com/ros/rosdistro/pull/21334) to be merged first? An alternative approach would be to fix the dps-for-iot build scripts to only call python-config when the python binding is enabled (which it is not in dps_for_iot_cmake_module).

I'm lacking some context, what are the Python bindings for? if you don't foresee these being used for rmw_dps then adjusting the build script in dps-for-iot makes sense. I noticed that right now the build succeeds anyway even if you don't have python-config installed (it complains but still goes through).

**Comment by malsbat** [comment]
The Python bindings are one of the supported bindings for the dps library.  The dps bindings can be enabled/disabled via scons variables, and none of the dps bindings apply to rmw_dps.  I filed https://github.com/intel/dps-for-iot/issues/103 to fix the issue inside dps-for-iot.

**Comment by malsbat** [comment]
@AAlon, I just closed https://github.com/intel/dps-for-iot/issues/103, I believe you can abandon this PR now.

**Pull request closed without merging**
