### PR TITLE
Safely convert from uint64_t to size_t.

### LINKED ISSUE #8: size_t cross-compilation issue
## Bug report

I'm trying to cross-compile this repository for RaspberryPi (32 bit)

The cross-compilation of this package fails because `deserializeSequenceSize` function takes a `size_t` argument and then converts it into `uint64_t.

https://github.com/ros2/rmw_dps/blob/master/rmw_dps_cpp/include/rmw_dps_cpp/CborStream.hpp#L444

```
error: cannot convert ‘size_t* {aka unsigned int*}’ to ‘uint64_t* {aka long long unsigned int*}’ for argument ‘3’ to ‘DPS_Status CBOR_Peek(DPS_RxBuffer*, uint8_t*, uint64_t*)’
     DPS_Status ret = CBOR_Peek(&buffer_, &maj, size);
```

Do you think that it is possible to change the `GenericCSequence` object to directly use the proper type?

https://github.com/ros2/rmw_dps/blob/ab6f8d0257d6cf61fc499fee6ab3936e0b3234f6/rmw_dps_cpp/include/rmw_dps_cpp/macros.hpp

### PR DESCRIPTION
**Pull request by malsbat**
This fixes #8.

Signed-off-by: Todd Malsbary <todd.malsbary@intel.com>

### CODE REVIEW

**Comment by malsbat** [comment]
@alsora, I can't seem to add you as a reviewer.  Please leave a comment if this fixes #8.

**Comment by alsora** [comment]
Thank you, this fixes #8 .

However, during my previous cross-compilation I haven't noticed that the underlying `DPS` library was not receiving the cross-compilation flags.
As a result `DPS` was still built for X86_64.

If I try to build `DPS` on 32 bit I get several similar errors.

For this reason I think that this PR should wait for `DPS` to be eventually updated with https://github.com/intel/dps-for-iot/issues/96

**Comment by malsbat** [comment]
I started an x86 branch for DPS here: https://github.com/intel/dps-for-iot/tree/x86.

**Comment by malsbat** [comment]
I'm going to merge this as it addresses the immediate issue.  The general cross-compilation of rmw_dps will be done in a different PR.

**Pull request merged**
